### ISSUE TITLE
Feature Request: openthesaurus.de backend

### ISSUE THREAD

**Issue by dunkla** [Ron89/thesaurus_query.vim#15]
It has an api and should serve better in longterm than woxikon..

**Comment by Ron89** [comment]
Thanks for pointing out, didn't notice it has open API before. I'll read about it and see to implement it when I have time again. Also, if you are interested, you can write a backend yourself. It's quite simple and straight forward: just write an `..._lookup.py` and put it under `autoload/thesaurus_query/backends`, the plugin will recognize it on next boot-up, referring the backend by its `identifier` and `language`. You can write any query routine, just make sure your backend has a `def query(target):` so that the plugin can call with.
For examples, you may refer to:
https://github.com/Ron89/thesaurus_query.vim/blob/master/autoload/thesaurus_query/backends/woxikon_de_lookup.py
and 
https://github.com/Ron89/thesaurus_query.vim/blob/master/autoload/thesaurus_query/backends/datamuse_com_lookup.py

**Comment by Ron89** [comment]
@dunkla , as requested, openthesaurus.de is now added as one of the default plugins. Please test if it is working fine for you.

**Comment by dunkla** [comment]
Sry for the late answer. It works as wished (openthesaurus is used by default and delviers good results).
