### ISSUE TITLE
cilin_txt backend cannot work

### ISSUE THREAD

**Issue by ChenWeird** [Ron89/thesaurus_query.vim#41]
I downloaded "cilin.txt" from [shijiebei2009/Algorithms](https://github.com/shijiebei2009/Algorithms/blob/master/src/main/resources/cilin.txt) , and make sure that cilin.txt is utf-8 encoded. But the plugin still do not function correctly with the file.

![GIF Demo](https://i.bmp.ovh/imgs/2019/03/45eeb551f050864a.gif)

![cilin error](https://i.bmp.ovh/imgs/2019/03/76413ebda7ed7d12.png)

My .vimrc setting:
```
let g:tq_openoffice_en_file=$HOME . "/.vim/thesaurus/MyThes-1.0/th_en_US_new"
let g:tq_mthesaur_file=$HOME . "/.vim/thesaurus/mthesaur.txt"
let g:tq_cilin_txt_file=$HOME . "/.vim/thesaurus/cilin.txt"
let g:tq_enabled_backends=["thesaurus_com","openoffice_en","mthesaur_txt","datamuse_com","cilin_txt"]
let g:tq_language=['en', 'cn']
```
Other backends is working well.

**Comment by ChenWeird** [comment]
chinese
![](https://i.bmp.ovh/imgs/2019/03/49a3ea364a8abfca.gif)

**Comment by ChenWeird** [comment]
error spell
![](https://i.bmp.ovh/imgs/2019/03/5f69b7d662bfdc74.gif)

**Comment by Ron89** [comment]
Hi, @ChenWeird , I think both comments refers to a same issue. Cilin text file has some encoding issue. The reason error spell lead to error is that thesaurus.com query didn't manage to find any positive hit. So cilin_txt is activated.
I did some searching on stackover flow, it is possible that your file is encoded in ISO-8869-1 instead of UTF-8. Code you try properly decoding it before encoding it again?
https://stackoverflow.com/questions/25599816/unicodedecodeerror-utf8-codec-cant-decode-byte-0xba-in-position-1266-invali

I am not familiar with Windows, but this link might help in re-encoding the file
https://superuser.com/questions/1163753/converting-text-file-to-utf-8-on-windows-command-prompt

**Comment by Ron89** [comment]
@ChenWeird , any updates on this issue?

**Comment by Ron89** [comment]
Closing now due to lack of confirmation on the issue.
